---

- name: "configuration play." 
  hosts: prometheus
  user: ubuntu
  become: true
  gather_facts: false 
  vars:
    - ansible_python_interpreter: /usr/bin/python3 
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml 
  
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600

    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false
      
  tasks:
    - name: Create Prometheus system group
      shell: | 
        groupadd --system prometheus
        useradd -s /sbin/nologin --system -g prometheus prometheus

    - name: Create data & configs directories for Prometheus
      shell: | 
        mkdir /var/lib/prometheus
        for i in rules rules.d files_sd; do sudo mkdir -p /etc/prometheus/${i}; done

    - name: Install prometheus 
      shell: | 
        mkdir -p /tmp/prometheus && cd /tmp/prometheus
        curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest | grep browser_download_url | grep linux-amd64 | cut -d '"' -f 4 | wget -qi - 
        tar xvf prometheus*.tar.gz
        cd prometheus*/ 
        mv prometheus promtool /usr/local/bin/  

    - name: Check installed version
      shell: | 
        prometheus --version
        promtool --version  
        echo """
          global:
            scrape_interval:     15s
            external_labels:
              monitor: 'codelab-monitor'
          scrape_configs:
            - job_name: 'prometheus'
              scrape_interval: 5s
              static_configs:
                - targets: ['localhost:9090']
        """ > prometheus.yml
        mv prometheus.yml /etc/prometheus/prometheus.yml
        mv consoles/ console_libraries/ /etc/prometheus/

    - name: Reload systemd daemon and start the service
      shell: |
        systemctl daemon-reload
        systemctl start prometheus 
        systemctl enable prometheus 

    - name: Check status using systemctl status prometheus command 
      shell: |
        systemctl status prometheus


  # roles:
  #   - configure-prometheus-server 


