---

- name: "configuration play." 
  hosts: prometheus
  user: ubuntu
  become: true
  gather_facts: false 
  vars:
    - ansible_python_interpreter: /usr/bin/python3 
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml 
  
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600

    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false
      
  tasks:
    - name: Download Prometheus
      shell: | 
        wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz

    - name: Unzip Prometheus
      shell: | 
        tar xzvf prometheus-2.19.0.linux-amd64.tar.gz

    - name: ls prometheus folder
      shell: | 
        cd prometheus-2.19.0.linux-amd64 
        ls -la 

    - name: Check installed version
      shell: | 
        ls -la 
        ./prometheus --version

  # roles:
  #   - configure-prometheus-server 


